### ISSUE TITLE
Critical errors in translated utterances

### ISSUE THREAD

**Issue by pahenning** [alexa/massive#4]
I have checked the de-DE file and find various utterances that have not been translated properly. No German speaker would use these words

Examples 
id 286: "die lichter in der küche anzünden"
id 6160: "outlet an"

**What I miss is a workflow for correcting such errors.**

Furthermore, some of the utterances in the data are pure garbage. 

Examples
id 511 is labeled as "weather_query" and contains the utterance "richtiger formel bitte" - meaning "correct formula please". This is syntactically as well as semantically incorrect.

id 523 is also labeled as "weather_query" and contains the utterance "es ist ein sehr gefährlicher" - meaning "it is a very dangerous one". Just absurd, this entry.

After checking several other domains I find that at least in the de-DE data a critical number of such errors exists. 
**I therefore raise the issue that the data quality is very far from being sufficient for meaningful tests.**

Regards

Peter Henning
Professor for Computer Science

**Comment by jgmf-amazon** [comment]
Hi Professor Henning,
Thanks for your feedback. One thing we haven't fully emphasized is that we include the judgment scores for each utterance. In the case of utterance 511, 2 out of 3 raters tagged `intent_score` as 0, meaning that the utterance does not match the intent. With utterance 523, all three raters put a score of 0 for `intent_score`.

In both of these cases, the English seed data didn't match the intent. For our work, we chose to localize and translate the entirety of the SLURP dataset, including utterances like these. Though we performed several cycles of re-translation and re-localization for low-quality translations and localizations, we didn't modify the underlying seed data. However, we have provided the judgment scores such that the end user can perform filtering as needed.

That said, if you find utterances with high judgment scores and which are poor quality, please let us know. Otherwise, we hope that you can find the data useful after filtering.

Thanks.

P.S. we are considering the creation of a "high quality" version of the dataset in which we perform the filtering and create an "official" post-filtered dataset.

**Comment by jgmf-amazon** [comment]
Hi Professor Henning,
I'm closing this out for now, but please re-open if you have any additional points or concerns. Thanks.

jgmf
